# Site settings
author: Shamel Lakin
title: Code Loud
header-img: img/home-bg.png
email: christlife4u@gmail.com
copyright_name: Shamel Lakin
description: > # this means to ignore newlines until "baseurl:"
  Writing code to change the world
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ShamelLakin
github_username:  ShamelLakin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
